### ISSUE TITLE
New Feature: Add flag to exclude bottom app bar or auto exclude it for single page PDFs

### ISSUE THREAD

**Issue by markathomas** [CrossPT/flutter_plugin_pdf_viewer#1]
I have an app where all PDFs are one page.  It's a waste of space for me to have the bottom app bar present.  A flag to remove this would be nice.

**Comment by CrossPT** [comment]
Thanks for the idea. Will do in next update.

**Comment by gegobyte** [comment]
@CrossPT I am creating an app which only shows 1 page pdf, it will be great if there is an option to disable the bottom indicators as there is just a single pdf page.
