### ISSUE TITLE
When opening another PDF from file path on iOS the first page shown belongs to the previously shown document

### ISSUE THREAD

**Issue by rwbr** [CrossPT/flutter_plugin_pdf_viewer#13]
There seems to be a bug in the iOS part of the plugin. My widget code around the PDFViewer looks like this:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_plugin_pdf_viewer/flutter_plugin_pdf_viewer.dart';
import 'dart:io';

class PdfViewerWidget extends StatelessWidget {
  PdfViewerWidget({Key key, this.document, this.title}) : super(key: key);
  final File document;
  final String title;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: PDFDocument.fromFile(document),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        if (snapshot.hasData) {
          if (snapshot.data != null) {
            return Scaffold(
              appBar: AppBar(
                title: Text(title),
              ),
              body: Center(
                child: PDFViewer(document: snapshot.data)
              )
            );
          }
        }
        return Center(
          child: CircularProgressIndicator()
        );
      },
    );
  }
}
```

I create this widget on a tap on an element in another widget, setting the document as a parameter of the call. The PDFViewer knows the correct path of the document and the document exists in the local documents directory of the app. I checked that. 

When I create the widget a second time (after leaving the view) with another document as parameter, the first page of the rendered PDF belongs to the previously shown document. After turning the page to page number 2 the 2nd page of the document is rendered correctly. Going back to page 1 shows the wrong page again.

I was not able to reproduce that on Android, so I guess, there is a problem inside the native iOS code.

**Comment by rwbr** [comment]
It's a bit different, than described before:
When I open another PDF, the first page always belongs to the previous document. But after I turned the first 8 or 10 pages and jump back to page 1 using the most left button in the tool bar, the first page is rendered correctly.

**Comment by CrossPT** [comment]
Thanks, will check.

**Comment by rwbr** [comment]
Were you unable to reproduce it?

**Comment by CrossPT** [comment]
Oh sorry, i didn't meant to close it... wrong button

**Comment by CrossPT** [comment]
Will take a look at this once i get home from work

**Comment by rwbr** [comment]
I tracked it down a little bit. I suppose, it has to do with some kind of caching. The iOS code seems to work properly. Also the rendered image in the file system has the correct content. But the widget loads a wrong image. That happens not every time, but very often. 

After I modified the ```_repaint()```-method of ```page.dart``` like that:

```dart
  _repaint() {
    imageCache.clear();
    provider = FileImage(File(widget.imgPath));
    final resolver = provider.resolve(createLocalImageConfiguration(context));
    resolver.addListener((imgInfo, alreadyPainted) {
      if (!alreadyPainted) setState(() {});
    });
  }
```

it shows the correct page every time. This change seems kind of ineffective in terms of performance. The caches should get reset only when necessary. Maybe you find a better solution.

**Comment by CrossPT** [comment]
Hi.
Thanks for your feedback. I just managed a solution without forcing the flutter image cache to be clean. For some reason ios was not overwrite the stored page (image) if it existed when we were loading it.

**Comment by CrossPT** [comment]
Will launch an update with this fix

**Comment by KaeganClark** [comment]
@CrossPT Just imported this plug in and like rwbr said I have to add ```imageCache.clear();``` to the page.dart file to get it to work correctly.
