### ISSUE TITLE
Error when build iOS with Flutter Version v1.7.0 (Dev Channel)

### ISSUE THREAD

**Issue by os20** [CrossPT/flutter_plugin_pdf_viewer#20]
compiler message:
file:///Users/oliverstannarius/Documents/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_pdf_viewer-1.0.6/lib/src/page.dart:33:26: Error: The argument type 'Null Function(dynamic, dynamic)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/name/Documents/Tools/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    resolver.addListener((imgInfo, alreadyPainted) {
                         ^
Compiler failed on /Users/name/Documents/Programmierung/FlutterProjects/am_app/lib/main.dart
Error launching application on iPhone Xs.

Flutter Doctor:
_app$ flutter doctor -v
[✓] Flutter (Channel dev, v1.7.0, on Mac OS X 10.14.5 18F132, locale de-DE)
    • Flutter version 1.7.0 at /Users/oliverstannarius/Documents/Tools/flutter
    • Framework revision f36a35d20a (4 days ago), 2019-05-31 15:27:56 -0400
    • Engine revision a32df2c928
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 445a23a9bc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/name/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/name/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.5.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • SM G930F 
    • android-arm64 • Android 8.0.0 (API 26)
    • iPhone Xs 
    • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

What can I do?

**Comment by CrossPT** [comment]
Closed (Duplicated #21). A new version was released to fix this issue
