### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by da7om85** [CrossPT/flutter_plugin_pdf_viewer#23]
`Compiler message:
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_pdf_viewer-1.0.6/lib/src/page.dart:35:26: Error: The argument type 'Null Function(dynamic, dynamic)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///C:/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    resolver.addListener((imgInfo, alreadyPainted) {
`

**Comment by Gardnem6** [comment]
Not a maintainer, but I took a closer look at this.  It appears 
`resolver.addListener((imgInfo, alreadyPainted) {
      if (!alreadyPainted) setState(() {});
    });
  }`

needs to be converted to `resolver.addListener(ImageStreamListener((imgInfo, alreadyPainted) {
      if (!alreadyPainted) setState(() {});
    }));`, but when I try to run that on flutter 1.7.8 I'm getting a CTD from the android runtime.

`E/AndroidRuntime( 9147): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-2
E/AndroidRuntime( 9147): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime( 9147): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime( 9147): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime( 9147): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime( 9147): 	at pt.tribeiro.flutter_plugin_pdf_viewer.FlutterPluginPdfViewerPlugin$1.run(FlutterPluginPdfViewerPlugin.java:44)
E/AndroidRuntime( 9147): 	at java.lang.Thread.run(Thread.java:764)`

**Comment by mrafsyam** [comment]
Had the same isssue...any fix or workaround?

**Comment by MichalMisiaszek** [comment]
Check  #21

**Comment by CrossPT** [comment]
Hi, new version was released

**Comment by CrossPT** [comment]
Closed (Duplicated #21)
