### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by wangbo4020** [CrossPT/flutter_plugin_pdf_viewer#29]
Because flutter_plugin_pdf_viewer >=1.0.7 depends on flutter_advanced_networkimage ^0.5.0 which depends on flutter_svg ^0.13.0, flutter_plugin_pdf_viewer >=1.0.7 requires flutter_svg ^0.13.0.
So, because app depends on both flutter_svg ^0.14.0 and flutter_plugin_pdf_viewer ^1.0.7, version solving failed.
pub get failed (1)

**Comment by felipeszu** [comment]
How did you solved this?

**Comment by wangbo4020** [comment]
> How did you solved this?

Continue to use 0.13.0

**Comment by wangbo4020** [comment]
Wait for flutter_advanced_networkimage to release the update

**Comment by wangbo4020** [comment]
flutter_advanced_networkimage upgraded

**Comment by wangbo4020** [comment]
@felipeszu you can see https://github.com/wangbo4020/flutter_plugin_pdf_viewer
