### ISSUE TITLE
Crash when clicking page selector with one page document

### ISSUE THREAD

**Issue by ksilz** [CrossPT/flutter_plugin_pdf_viewer#35]
I have an app where I show one page PDF documents. When I click on the widget at the bottom, it crashes:

![PDF Viewer crash](https://user-images.githubusercontent.com/1061209/64038810-f9c88100-cb50-11e9-91de-792bc5cd7545.gif)

I think the `NumberPicker` you use doesn't work when `minValue` and `maxValue` are the same. [Here's the code](https://github.com/CrossPT/flutter_plugin_pdf_viewer/blob/master/lib/src/viewer.dart#L102).

**Comment by magnus-lpa** [comment]
Duplicate of #28 

See #28 for possible workarounds.

**Comment by ksilz** [comment]
Yep, workaround works for me.

**Comment by gegobyte** [comment]
If you know in advance that your app will always show one page Pdf's only then you can set `showPicker` to `false` in your code to hide the picker.

```dart
PDFViewer(
    document: pdfDoc,
    showPicker: false,
)
```
