### ISSUE TITLE
Xcode build error

### ISSUE THREAD

**Issue by mrsensen** [CrossPT/flutter_plugin_pdf_viewer#8]
<img width="1119" alt="WX20190328-155536@2x" src="https://user-images.githubusercontent.com/12557001/55139996-0267f600-5172-11e9-8d53-1d47f4723316.png">

**Comment by CrossPT** [comment]
Hi, i launched a new version that fixes this issue, based on PR #6 .

My iPhone is currently in repair due to screen bleeding. I couldn't test this. Please test and give feedback if it worked.

**Comment by mrsensen** [comment]
thx, but there is new question
<img width="1128" alt="WX20190329-143813@2x" src="https://user-images.githubusercontent.com/12557001/55214055-736de300-5230-11e9-9329-15401ffb6306.png">
this is my version
<img width="691" alt="WX20190329-143744@2x" src="https://user-images.githubusercontent.com/12557001/55214077-84b6ef80-5230-11e9-975a-28d7852e09fd.png">

**Comment by CrossPT** [comment]
Hi, after debugging found that the issue is related to path_provider, will do a fix asap

**Comment by CrossPT** [comment]
Hi, try new update as i did some pod changes although i couldn't replicatr this issue

**Comment by CrossPT** [comment]
Closed. Reason: stalled
