### ISSUE TITLE
White background for iOS

### ISSUE THREAD

**Issue by allanwolski** [CrossPT/flutter_plugin_pdf_viewer#9]
Great job with this plugin, @CrossPT 

Could you replicate the changes to add a white background in iOS too? I do not know how to do this.
https://github.com/CrossPT/flutter_plugin_pdf_viewer/commit/7be50054a2d44eb8c0d7e0819833180514033ce9

Can you increase the image quality generated from the PDF to iOS?

**Comment by CrossPT** [comment]
Hi. Just launched version 1.0.4 :)

**Comment by allanwolski** [comment]
@CrossPT 

The resolution of the generated PDF image on iOS is still low compared to Android.

https://user-images.githubusercontent.com/11680596/56522236-954f4280-651c-11e9-939d-dfcdd3d130b5.jpg

https://user-images.githubusercontent.com/11680596/56522298-a4ce8b80-651c-11e9-962f-4ada820abfb4.png
