### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty on  advance_pdf_viewer: ^1.2.0

### ISSUE THREAD

**Issue by ziasultan2** [CrossPT/flutter_plugin_pdf_viewer#92]
Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:26:52)
#1      _PDFViewerState._loadPage (package:advance_pdf_viewer/src/viewer.dart:140:15)
#2      _PDFViewerState.didChangeDependencies (package:advance_pdf_viewer/src/viewer.dart:119:5)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4705:12)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:

**Comment by gtu-myowin** [comment]
In my case, it is the file name which was in UTF-8 characters. Once I changed the pdf file name to english letters, `advance_pdf_viewer` can read it with or without .pdf extension.
